### ISSUE TITLE
APIRequestArgument doesn't support Arrays or Dictionaries

### ISSUE THREAD

**Issue by RobertManeaSST** [okta/okta-mobile-swift#111]
### Describe the bug?

I didn't know whether to log this here, or on the OktaIdx github. But I'm considering it a bug, since OktaIdx is able to use APIRequestArgument for types it isn't compatible with, and this is something that can be fixed by a change within this SDK, so here's what happens:

I've got a Remediation.Form.Field object that has an option and that option has a nested structure within its value field that I can't get through in the OktaIdx SDK, due to the fact that the value property is returned via its custom get(): _value as? APIRequestArgument, which works just fine, but only when working with primitive types.

I'm assuming just appending

`extension [Any]: APIRequestArgument {
    public var stringValue: String { "\(self)" }
}

extension [AnyHashable: Any]: APIRequestArgument {
    public var stringValue: String { "\(self)" }
}`

to the APIRequestArgument file would fix the issue, but I have no idea whether this classifies as an Obvious Bug so I don't know whether to create a PR with it. Not to mention that we'd still need OktaIdx to be updated to require whatever new version of OktaAuthFoundation would result out of this change.

### What is expected to happen?

Remediation.Form.Field's value object should be able to contain and return arrays and dictionaries.

### What is the actual behavior?

Arrays and Dictionaries are returned as null due to the fact that the value property is "converted" to an APIRequestArgument object, which in a protocol not supported by arrays and dictionaries.

### Reproduction Steps?

-

### SDK Version(s)

OktaIdx 3.0.7, OktaAuthFoundation 1.2.0

**Comment by mikenachbaur-okta** [comment]
Hi @RobertManeaSST, since options within the API behave differently than string or numeric primitive values, selecting an option uses a different property. To select an option, you assign the value to the parent field's [selectedOption](https://okta.github.io/okta-idx-swift/development/oktaidx/documentation/oktaidx/remediation/form-swift.class/field/selectedoption) property.

**Comment by RobertManeaSST** [comment]
Hi @mikenachbaur-okta. Actually, my problem was that our structure was attempting to use options, but it really only showed me one option (and I actually wanted to view said options so that I could show them to the user). So I don't know whether it's a problem with the SDK not parsing the JSON structure properly or whether our API guys improperly implemented the response here.

Regardless, I've rushed into creating this issue. I ended up just creating extensions for Array and Dictionary within our app's code so that I may parse the response and get the things I needed.

```
extension Array: APIRequestArgument {
public var stringValue: String { "(self)" }
}

extension Dictionary: APIRequestArgument {
public var stringValue: String { "(self)" }
}
```

I'm happy to close this ticket if there's nothing else you think would be worth investigating.

**Comment by mikenachbaur-okta** [comment]
I'm not sure if that will work out for you in the long term, because under some circumstances the options may themselves have values that require user input (for example, options are used within Security Question authenticators, some of which may require a user to submit their own question and answer).  This is the reason why we implemented the "selectedOption" approach, since as a developer, you are choosing one sub-tree of fields to be submitted to the server for a given parent field.

The README has a few examples of how to use options, such as [enrolling in a security question](https://github.com/okta/okta-idx-swift#enrolling-a-security-question-authenticator), which might help in the patterns you can use when interacting with options.
