### ISSUE TITLE
Could not set up a provider for handling web authentication.

### ISSUE THREAD

**Issue by jiaqi-transcarent** [okta/okta-mobile-swift#165]
### Describe the bug?

The app suddenly stopped working at one point, and never been able to log in ever since, get the error message in the log that goes "Could not set up a provider for handling web authentication". What are some possible causes for this error? This error is so far only reproducible by a small portion of our users. ( The okta configuration is the same for all users. )

### What is expected to happen?

After ASWebAuthenticationSession navigates back to app after sign-in, app receives the JWT token.

### What is the actual behavior?

After ASWebAuthenticationSession navigates back to app after sign-in and throws an error.

### Reproduction Steps?

```swift
        guard let vc = UIApplication.shared.windows.filter({ $0.isKeyWindow }).first?.rootViewController else { return }
        let token = try await ssoOktaAuth.signIn(from: vc.view.window, options: options)
```

### SDK Version(s)

1.4.2

**Comment by mikenachbaur-okta** [comment]
Hi @jiaqi-transcarent, the [authenticationProviderError](https://okta.github.io/okta-mobile-swift/development/webauthenticationui/documentation/webauthenticationui/webauthenticationerror/authenticationprovidererror(_:)) is returned when the authentication provider (in this case ASWebAuthenticationSession) reports an error to the SDK.  It includes the underlying error reported by ASWebAuthenticationSession which can be used to further debug the issue.

I suggest you attempt to unwrap the error within your catch block to see what the root cause is. 

The two places where this can be thrown is when [ASWebAuthenticationSession returns an error object](https://github.com/okta/okta-mobile-swift/blob/master/Sources/WebAuthenticationUI/Providers/AuthenticationServicesProvider.swift#L169), and when [exchanging the resulting URL results in an error](https://github.com/okta/okta-mobile-swift/blob/master/Sources/WebAuthenticationUI/Providers/AuthenticationServicesProvider.swift#L182).

**Comment by jiaqi-transcarent** [comment]
> Hi @jiaqi-transcarent, the [authenticationProviderError](https://okta.github.io/okta-mobile-swift/development/webauthenticationui/documentation/webauthenticationui/webauthenticationerror/authenticationprovidererror(_:)) is returned when the authentication provider (in this case ASWebAuthenticationSession) reports an error to the SDK. It includes the underlying error reported by ASWebAuthenticationSession which can be used to further debug the issue.
> 
> I suggest you attempt to unwrap the error within your catch block to see what the root cause is.
> 
> The two places where this can be thrown is when [ASWebAuthenticationSession returns an error object](https://github.com/okta/okta-mobile-swift/blob/master/Sources/WebAuthenticationUI/Providers/AuthenticationServicesProvider.swift#L169), and when [exchanging the resulting URL results in an error](https://github.com/okta/okta-mobile-swift/blob/master/Sources/WebAuthenticationUI/Providers/AuthenticationServicesProvider.swift#L182).

The issue went away by itself after I bumped the version from 1.4.2 to 1.5.0. Thanks for you quick response!
